### ISSUE TITLE
[Bug] Finder eyes blink incorrectly

### ISSUE THREAD

**Issue by 3raxton** [neilsardesai/Mouse-Finder#6] opened 2022-03-01 17:01 UTC
Hey @neilsardesai, great work again on Mouse Finder! I love how it makes my Mac unique and appreciate the work you put into it. I recently built it from the Xcode file on Github and I'm dealing with an odd issue. 

Once running, the blink animation zooms in and out instead of actually blinking. I'm not the best with Xcode so I can't quite figure out what is going on and I figured I'd open an issue to see if you had any ideas why this was happening or what I could do to solve it. Does anything come to mind?

Thanks again for your hard work! Love your stuff and can't wait to see what comes next!

If the attached video will not load please view it here: https://imgur.com/a/dGlZfu4

https://user-images.githubusercontent.com/20716142/156214123-3d04303e-3e6e-4092-ae91-4b8eb7b608da.mov

**Comment by neilsardesai** [comment] 2022-03-03 23:40
Hey Braxton, that’s def weird. Unfortunately I can’t reproduce this on my end. Are you also seeing this issue when you run the release build, rather than building it off of Xcode?

**Comment by 3raxton** [comment] 2022-03-04 00:00
Hey Neil, thanks for the response. I am seeing it from the release build and when built from Xcode. Do you have any idea what I should try to fix this? Thanks!

**Comment by neilsardesai** [comment] 2022-03-04 00:08
Hmm, dang, honestly I have no idea, since I can’t reproduce this on my end 🙁. I’m going to close this for now but if you can figure out what’s causing the issue, I’d be happy to review a PR. Alternatively, maybe you could tweak the code for your local build to just never have the eyes blink 👁👁

**Closed as completed by neilsardesai** 2022-03-04 00:08 UTC

**Comment by 3raxton** [comment] 2022-03-04 00:12
Go for it, I’ll follow up with you here if there is anything I notice or that comes to mind. May just need to turn off the blinking as a whole.

Thanks for your support & your great work! Be well!
